all:
  hosts:
    master01:
      ansible_host: 
      ip: 
      acces_ip: 
    master02:
      ansible_host: 
      ip: 
      acces_ip: 
    master03:
      ansible_host: 
      ip: 
      acces_ip: 
    etcd-node1:
      ansible_host: 
      ip: 
      acces_ip: 
    etcd-node2:
      ansible_host: 
      ip: 
      acces_ip: 
    etcd-node3:
      ansible_host: 
      ip: 
      acces_ip: 
    worker01:
      ansible_host: 
      ip: 
      acces_ip: 
    worker02:
      ansible_host: 
      ip: 
      acces_ip: 
    worker03:
      ansible_host: 
      ip: 
      acces_ip: 
    worker04:
      ansible_host: 
      ip: 
      acces_ip: 
  children:
    kube-master:
      hosts:
        master01:
        master02:
        master03:
    kube-node:
      hosts:
        worker01:
        worker02:
        worker03:
        worker04:
    etcd:
      hosts:
        etcd-node1:
        etcd-node2:
        etcd-node3:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: { }



